/* Generated by autorevision - do not hand-hack! */

#ifndef MSCOMPRESS_AUTOREVISION_H
#define MSCOMPRESS_AUTOREVISION_H

#include <string>

namespace mscompress
{
	const std::string VCS_TYPE		= "git";
	const std::string VCS_BASENAME	= "ms_compress";
	const std::string VCS_UUID		= "371bfdd993815fdde4fd792d400ab74211c55940";
	const int VCS_NUM				= 875;
	const std::string VCS_DATE		= "2016-12-22T17:12:00Z";
	const std::string VCS_BRANCH	= "feature/PMI-1658_last_func";
	const std::string VCS_TAG		= "v1.2";
	const int VCS_TICK				= 501;
	const std::string VCS_EXTRA		= "";

	const std::string VCS_ACTION_STAMP	= "2016-12-22T17:12:00Z!d_kletter@yahoo.com";
	const std::string VCS_FULL_HASH		= "232264a91eaa316ddcd6adcb20335656715bc7a4";
	const std::string VCS_SHORT_HASH	= "232264a";

	const int VCS_WC_MODIFIED			= 0;
}

#endif

/* end */
